%YAML:1.0

#camera calibration
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480

   k1: 0.148000794688248
   k2: -0.217835187249065
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 617.971050917033
   fy: 616.445131524790
   cx: 327.710279392468
   cy: 253.976983707814